### ISSUE TITLE
Fallo Bot no inicializa

### ISSUE THREAD

**Issue by thepema** [Proyecto-EGC-G1/CabinaTelegram-EGC-G1#12]
Al pasar el bot de Windows a Linux, me da un fallo donde no reconoce bien el codigo cuando en Windows era totalmente funcional y tiene node y java instalado en la maquina virtual.

**Comment by migmogcam** [comment]
Creo que tu problema tiene q ver con la versión de Node o de Npm, te he subido en una carpeta unas guías, mírate la de "Actualizar Node y Npm en linux.txt ". eso es lo que he hecho para que me funcione.

**Comment by thepema** [comment]
Perfecto ya funciona.
