### ISSUE TITLE
Proporcionar número de votantes

### ISSUE THREAD

**Issue by jorgegarciax2** [Proyecto-EGC-G1/CabinaTelegram-EGC-G1#2]
Desde redes sociales y para ofrecer la funcionalidad de compartir un balance de participación de los votantes en una votación, necesitamos saber si existiría la posibilidad de que nos proporcionaseis el número de votantes de una votación.

El objetivo sería que el equipo de Cabina de Telegram implementase un contador a la hora de que los usuarios realicen una votación, de forma que podamos consultar dicho dato.

Desde integración nos han pedido llegar a un acuerdo

**Comment by thepema** [comment]
Desde cabina de Telegram de momento no creemos que sea posible porque no sabemos como poder implementar la gente que vaya a vota, poder se podría pero no es nuestro meta ahora mismo, con que de momento diría que no.

**Comment by jorgegarciax2** [comment]
En **la reunión del día 15** se llegó al acuerdo de que cabina de votaciones no será la encarga de realizar dicha función. La función la realizará almacenamiento de votos puesto que son los encargados de validar los votos.
