### ISSUE TITLE
Problema con ejecutar el bot

### ISSUE THREAD

**Issue by josromada** [Proyecto-EGC-G1/CabinaTelegram-EGC-G1#20]
Al intentar ejecutar el bot me salta el error "SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode". Busco en Google y se trata de un error con node y lo actualizo y sigue apareciendo lo mismo.

**Comment by migmogcam** [comment]
Ese tipo de errores son de la versión de node o el gestor npm, prueba con un 
>npm install
en tu carpeta del projecto y comprueba las versiones de node y npm

**Comment by migmogcam** [comment]
si aun no te funciona, prueba:
- ve a la carpeta del bot con el terminal (.../telebot)
-usa "sudo npm install mysql"
- y vuelve a usar "sudo npm init"
