### ISSUE TITLE
Integración continua con Travis CI

### ISSUE THREAD

**Issue by fracorvel** [Proyecto-EGC-G1/CabinaTelegram-EGC-G1#29]
Clonar el repositorio de GitHub a un nuevo entorno virtual y llevar a cabo una serie de tareas para construir y probar el código.

**Comment by fracorvel** [comment]
He añadido a migmogcam a la Tarea.

**Comment by migmogcam** [comment]
he añadido el documento travis que he estado probando, ya se puede añadir tests en la carpeta test del telebot.
