### ISSUE TITLE
Correción de la documentación

### ISSUE THREAD

**Issue by danielk012** [Proyecto-EGC-G1/CabinaTelegram-EGC-G1#9]
Falta por indicar un miembro del equipo (pag1).
Falta por definir etiquetas.
Falta un apartado que describa la funcionalidad del bot creado.
Falta describir cómo se pasa de las rama dev a la master.

**Comment by migmogcam** [comment]
Vale acabo de añadir todo eso. Comprueba los cambios y cierra esta Issue si crees que esta correcto. de lo contrario comenta por aquí.
